'use client'

import { useMemo, useState } from 'react'
import { Search, ShoppingBag, Menu, X, ChevronDown, Plus, Minus, ArrowRight, Sparkles, Check, MessageCircle } from 'lucide-react'

const brand = { name: 'PoojaSetu', tagline: 'Essentials for Every Sacred Occasion' }

type Product = { id: string; name: string; category: string; festivals: string[]; price: number; unit: string; description: string; image: string }
const products: Product[] = [
  { id:'daily-kit', name:'Daily Pooja Starter Kit', category:'Pooja Kits', festivals:['Daily Pooja'], price:699, unit:'18 essentials', description:'A thoughtful foundation for everyday worship.', image:'/pooja-hero.png' },
  { id:'navratri-kit', name:'Navratri Pooja Essentials Kit', category:'Pooja Kits', festivals:['Navratri'], price:899, unit:'14 essentials', description:'A considered collection for the nine sacred days.', image:'/pooja-hero.png' },
  { id:'diwali-kit', name:'Diwali Lakshmi–Ganesh Pooja Kit', category:'Pooja Kits', festivals:['Diwali'], price:1299, unit:'22 essentials', description:'Prepare your home for a luminous Diwali ritual.', image:'/pooja-hero.png' },
  { id:'bhai-dooj', name:'Bhai Dooj Roli–Akshat Set', category:'Gifts', festivals:['Bhai Dooj'], price:349, unit:'1 festive set', description:'A graceful thali for a treasured tradition.', image:'/pooja-hero.png' },
  { id:'chhath', name:'Chhath Offering Accessories Set', category:'Gifts', festivals:['Chhath'], price:499, unit:'5 pieces', description:'Simple accessories for offering preparations.', image:'/pooja-hero.png' },
  { id:'kapoor', name:'Bhimseni Kapoor', category:'Daily Essentials', festivals:['Daily Pooja','Diwali'], price:189, unit:'50 g', description:'Pure, aromatic camphor for your daily aarti.', image:'/pooja-hero.png' },
  { id:'agarbatti', name:'Chandan Agarbatti', category:'Dhoop & Incense', festivals:['Daily Pooja'], price:149, unit:'40 sticks', description:'A gentle sandalwood fragrance for quiet moments.', image:'/pooja-hero.png' },
  { id:'dhoop', name:'Natural Dhoop Cones', category:'Dhoop & Incense', festivals:['Daily Pooja'], price:229, unit:'30 cones', description:'Hand-shaped cones with a warm, grounding aroma.', image:'/pooja-hero.png' },
  { id:'wicks', name:'Cotton Diya Wicks', category:'Diyas & Lamps', festivals:['Daily Pooja','Diwali'], price:99, unit:'100 wicks', description:'Soft cotton wicks for diyas and lamps.', image:'/pooja-hero.png' },
  { id:'diyas', name:'Clay Diyas', category:'Diyas & Lamps', festivals:['Diwali'], price:249, unit:'Pack of 12', description:'Unfired earthen diyas with a timeless form.', image:'/pooja-hero.png' },
  { id:'thali', name:'Brass Pooja Thali', category:'Daily Essentials', festivals:['Daily Pooja','Diwali'], price:1099, unit:'1 thali', description:'A lasting brass centrepiece for your altar.', image:'/pooja-hero.png' },
  { id:'kumkum', name:'Kumkum and Haldi Set', category:'Daily Essentials', festivals:['Daily Pooja','Bhai Dooj'], price:179, unit:'2 x 25 g', description:'Everyday auspicious essentials in a neat pair.', image:'/pooja-hero.png' },
  { id:'hawan', name:'Hawan Samagri', category:'Daily Essentials', festivals:['Navratri','Dussehra'], price:299, unit:'250 g', description:'A fragrant blend for your hawan preparations.', image:'/pooja-hero.png' },
  { id:'panchmeva', name:'Panchmeva Offering Mix', category:'Prasad & Bhog', festivals:['Daily Pooja','Navratri'], price:279, unit:'200 g', description:'A wholesome mix for offering and sharing.', image:'/pooja-hero.png' },
  { id:'mishri', name:'Mishri for Bhog', category:'Prasad & Bhog', festivals:['Daily Pooja','Diwali'], price:129, unit:'250 g', description:'Crystalline sweetness for your bhog thali.', image:'/pooja-hero.png' },
  { id:'gift-box', name:'Festive Pooja Gift Box', category:'Gifts', festivals:['Diwali','Bhai Dooj'], price:999, unit:'1 curated box', description:'A warm gesture for a sacred celebration.', image:'/pooja-hero.png' },
]
const filters = ['All','Pooja Kits','Daily Essentials','Prasad & Bhog','Diyas & Lamps','Dhoop & Incense','Gifts']
const occasions: Record<string,string[]> = { 'Daily Pooja':['Cotton Diya Wicks','Bhimseni Kapoor','Chandan Agarbatti','Kumkum and Haldi Set'], Navratri:['Navratri Pooja Essentials Kit','Hawan Samagri','Panchmeva Offering Mix'], Diwali:['Diwali Lakshmi–Ganesh Pooja Kit','Clay Diyas','Cotton Diya Wicks','Mishri for Bhog'], 'Bhai Dooj':['Bhai Dooj Roli–Akshat Set','Kumkum and Haldi Set'], Chhath:['Chhath Offering Accessories Set','Panchmeva Offering Mix'] }

export default function Page() {
  const [filter,setFilter] = useState('All'), [festival,setFestival] = useState(''), [query,setQuery] = useState(''), [cart,setCart] = useState<Record<string,number>>({}), [selected,setSelected] = useState<Product|null>(null), [cartOpen,setCartOpen] = useState(false), [menuOpen,setMenuOpen] = useState(false), [assistant,setAssistant] = useState(false), [occasion,setOccasion] = useState('Daily Pooja'), [checked,setChecked] = useState<string[]>([])
  const visible = useMemo(() => products.filter(p => (filter==='All'||p.category===filter) && (!festival||p.festivals.includes(festival)) && (!query||`${p.name} ${p.category} ${p.festivals.join(' ')}`.toLowerCase().includes(query.toLowerCase()))), [filter,festival,query])
  const count = Object.values(cart).reduce((a,b)=>a+b,0), subtotal = products.reduce((sum,p)=>sum+(cart[p.id]||0)*p.price,0)
  const add = (id:string) => setCart(c=>({...c,[id]:(c[id]||0)+1}))
  const change = (id:string, delta:number) => setCart(c=>{ const n=(c[id]||0)+delta; const next={...c}; if(n<=0) delete next[id]; else next[id]=n; return next })
  const scrollProducts = (nextFilter='All', nextFestival='') => { setFilter(nextFilter); setFestival(nextFestival); setTimeout(()=>document.getElementById('products')?.scrollIntoView({behavior:'smooth'}),30) }
  const kit = products.find(p=>p.id==='diwali-kit')!
  return <main className="site-shell">
    <div className="announcement">Explore essentials for the festive season <span>•</span> Thoughtfully prepared for your rituals</div>
    <header className="header"><button className="icon-btn mobile-only" aria-label="Open navigation" onClick={()=>setMenuOpen(true)}><Menu/></button><a className="logo" href="#top"><span className="diya">◒</span><span><strong>{brand.name}</strong><small>{brand.tagline}</small></span></a><nav className="desktop-nav"><a href="#products">Shop</a><a href="#festivals">Festival Collections</a><a href="#kits">Pooja Kits</a><a href="#bhog">Prasad & Bhog</a><a href="#story">Our Story</a></nav><div className="header-actions"><button className="icon-btn" aria-label="Search" onClick={()=>document.getElementById('search')?.focus()}><Search/></button><button className="cart-btn" onClick={()=>setCartOpen(true)} aria-label={`Open demo cart, ${count} items`}><ShoppingBag/><span>{count}</span></button></div></header>
    {menuOpen&&<div className="mobile-menu"><div className="mobile-menu-head"><span className="logo"><span className="diya">◒</span><strong>{brand.name}</strong></span><button className="icon-btn" onClick={()=>setMenuOpen(false)} aria-label="Close navigation"><X/></button></div><a href="#products" onClick={()=>setMenuOpen(false)}>Shop</a><a href="#festivals" onClick={()=>setMenuOpen(false)}>Festival Collections</a><a href="#kits" onClick={()=>setMenuOpen(false)}>Pooja Kits</a><a href="#bhog" onClick={()=>setMenuOpen(false)}>Prasad & Bhog</a><a href="#story" onClick={()=>setMenuOpen(false)}>Our Story</a></div>}
    <section id="top" className="hero"><div className="hero-copy"><p className="eyebrow">Celebrate with devotion</p><h1>Every ritual,<br/><em>thoughtfully prepared.</em></h1><p className="hero-text">Discover pooja essentials, festive kits, and prasad ingredients for the moments that bring us together.</p><div className="hero-actions"><button className="button primary" onClick={()=>scrollProducts('All','Diwali')}>Explore Festival Essentials <ArrowRight/></button><button className="text-button" onClick={()=>scrollProducts('Pooja Kits')}>Discover Pooja Kits</button></div></div><div className="hero-art"><div className="art-label">A little more meaning<br/><strong>in every detail</strong></div><img src="/pooja-hero.png" alt="Warm festive arrangement with diyas and pooja essentials"/><div className="art-stamp">शुभ<br/><small>auspicious beginnings</small></div></div></section>
    <section className="categories"><p className="eyebrow centered">Begin your journey</p><h2 className="centered">Find what your ritual needs</h2><div className="category-row">{['Pooja Kits','Prasad & Bhog','Dhoop & Incense','Diyas & Lamps','Daily Essentials','Gifts'].map((x,i)=><button className="category" key={x} onClick={()=>scrollProducts(x)}><span className={`category-image c${i}`}><img src="/pooja-hero.png" alt=""/></span><strong>{x}</strong></button>)}</div></section>
    <section id="festivals" className="section festivals"><div className="section-heading"><div><p className="eyebrow">Made for the moment</p><h2>Prepare for your next celebration</h2></div><p>Thoughtful essentials for every sacred occasion.</p></div><div className="festival-grid">{['Navratri','Dussehra','Diwali','Bhai Dooj','Chhath'].map((x,i)=><button key={x} className={`festival-card f${i} ${festival===x?'selected':''}`} onClick={()=>scrollProducts('All',x)}><img src="/pooja-hero.png" alt=""/><span>{x}</span><small>Explore essentials <ArrowRight/></small></button>)}</div></section>
    <section id="kits" className="section kits"><div className="section-heading"><div><p className="eyebrow">Gathered with care</p><h2>Your pooja essentials,<br/>brought together.</h2></div><p>Illustrative kits designed to make preparation feel simple. Contents may vary by regional tradition.</p></div><div className="kit-grid">{products.slice(0,3).map(p=><article className="kit-card" key={p.id}><div className="product-image"><img src={p.image} alt=""/><span>Preview kit</span></div><div className="kit-content"><h3>{p.name}</h3><p>{p.description}</p><small>{p.unit} · ₹{p.price.toLocaleString('en-IN')}</small><button className="outline-button" onClick={()=>setSelected(p)}>View Kit <ArrowRight/></button></div></article>)}</div></section>
    <section id="products" className="section browser"><div className="section-heading"><div><p className="eyebrow">The preview catalogue</p><h2>Essentials for every altar.</h2></div><p>Browse individual samagri and thoughtful gifts for your home.</p></div><div className="browser-controls"><div className="filter-row">{filters.map(x=><button key={x} className={filter===x?'active':''} onClick={()=>{setFilter(x);setFestival('')}}>{x}</button>)}</div><div className="search-wrap"><Search/><input id="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search the catalogue" aria-label="Search catalogue"/></div></div>{festival&&<div className="active-filter">Showing {festival} essentials <button onClick={()=>setFestival('')} aria-label="Clear festival filter"><X/></button></div>}<p className="result-count">{visible.length} sample products</p><div className="product-grid">{visible.map(p=><article className="product-card" key={p.id}><button className="product-image" onClick={()=>setSelected(p)}><img src={p.image} alt={p.name}/><span>View details</span></button><div className="product-info"><p>{p.category}</p><h3>{p.name}</h3><small>{p.unit}</small><div className="product-bottom"><strong>₹{p.price.toLocaleString('en-IN')}</strong><button className="add-button" onClick={()=>add(p.id)} aria-label={`Add ${p.name} to cart`}><Plus/></button></div></div></article>)}</div>{!visible.length&&<div className="empty"><Sparkles/><h3>Nothing found in this selection</h3><p>Try another category or clear your search.</p><button className="outline-button" onClick={()=>{setFilter('All');setFestival('');setQuery('')}}>Reset catalogue</button></div>}<p className="preview-note">Preview catalogue — products and prices are illustrative.</p></section>
    <section id="bhog" className="editorial"><div className="editorial-image"><img src="/pooja-hero.png" alt="Ingredients arranged for a devotional offering"/></div><div><p className="eyebrow">For offering and sharing</p><h2>Thoughtful offerings for your daily devotion.</h2><p>Explore ingredients intended for preparing or offering bhog at home. These are not represented as temple-offered prasad; details will be verified before launch.</p><button className="button dark" onClick={()=>scrollProducts('Prasad & Bhog')}>Explore Prasad & Bhog <ArrowRight/></button></div></section>
    <section className="checklist section"><div className="check-copy"><p className="eyebrow">A little help, when you need it</p><h2>Not sure what<br/><em>to prepare?</em></h2><p>Choose an occasion to see a simple list of suggested essentials. Tick what you already have at home.</p><p className="fine-print">Suggested essentials may vary by family and regional tradition.</p></div><div className="check-panel"><div className="occasion-tabs">{Object.keys(occasions).map(x=><button className={occasion===x?'active':''} key={x} onClick={()=>{setOccasion(x);setChecked([])}}>{x}</button>)}</div><div className="check-list">{occasions[occasion].map(name=>{const done=checked.includes(name); return <button className={`check-item ${done?'done':''}`} key={name} onClick={()=>setChecked(c=>done?c.filter(x=>x!==name):[...c,name])}><span>{done?<Check/>:<span/>}</span><strong>{name}</strong><small>{products.find(p=>p.name===name)?.category}</small></button>})}</div><button className="outline-button" onClick={()=>scrollProducts('All',occasion)}>Shop Remaining Essentials <ArrowRight/></button></div></section>
    <section id="story" className="story"><div><p className="eyebrow">The PoojaSetu approach</p><h2>Care in the essentials.<br/><em>Meaning in the ritual.</em></h2></div><p>We are building a more considered way to prepare for worship: browse by occasion, understand what is included, and find the everyday essentials that make a ritual feel like your own.</p><div className="values"><span>Clearly listed kit contents</span><span>Browse by occasion</span><span>Useful product information</span><span>Help finding your essentials</span></div></section>
    <section className="faq section"><div><p className="eyebrow">Questions, simply answered</p><h2>Good to know.</h2></div><div className="faq-list">{[['What is included in a pooja kit?','Kit contents can be viewed in each product detail. Sample contents are illustrative and may vary by regional tradition.'],['Can I purchase individual samagri items?','Yes. The preview catalogue includes individual daily essentials, incense, lamps, offerings, and gifts.'],['Are these products temple-offered prasad?','No claim is made here. Temple origin and product details will be verified before launch.'],['How do I find products for a particular festival?','Use the festival cards above or the product filters to browse by occasion.'],['Can I customise a kit?','Custom kits will be confirmed in a later phase.'],['Where can I check delivery and return details?','Operational delivery and return policies will be confirmed before launch.']].map(([q,a])=><details key={q}><summary>{q}<ChevronDown/></summary><p>{a}</p></details>)}</div></section>
    <footer><div className="footer-brand"><span className="logo"><span className="diya">◒</span><strong>{brand.name}</strong></span><p>{brand.tagline}</p><small>Preview catalogue for Phase 1.</small></div><div><strong>Shop</strong><a href="#products">All essentials</a><a href="#kits">Pooja kits</a><a href="#bhog">Prasad & Bhog</a></div><div><strong>Explore</strong><a href="#festivals">Festival collections</a><a href="#story">Our story</a><a href="#top">Back to top</a></div><div><strong>Phase 1</strong><p>Products and prices shown are illustrative. Checkout will be available after launch setup.</p></div></footer>
    <button className="assistant-launcher" onClick={()=>setAssistant(true)} aria-label="Open Pooja Assistant"><MessageCircle/><span>Pooja Assistant</span></button>
    {selected&&<div className="overlay" onClick={()=>setSelected(null)}><div className="quick-view" role="dialog" aria-modal="true" aria-label={selected.name} onClick={e=>e.stopPropagation()}><button className="close-btn" onClick={()=>setSelected(null)} aria-label="Close"><X/></button><img src={selected.image} alt={selected.name}/><div className="quick-copy"><p className="eyebrow">{selected.category}</p><h2>{selected.name}</h2><p>{selected.description}</p><strong className="quick-price">₹{selected.price.toLocaleString('en-IN')} <small>{selected.unit}</small></strong><div className="contents"><strong>Sample details</strong><p>Contents are illustrative and may vary by regional tradition. Ingredients and storage information will be confirmed before launch.</p></div><button className="button primary full" onClick={()=>{add(selected.id);setSelected(null);setCartOpen(true)}}>Add to demo cart <ShoppingBag/></button></div></div></div>}
    {cartOpen&&<div className="overlay" onClick={()=>setCartOpen(false)}><aside className="cart-drawer" onClick={e=>e.stopPropagation()}><div className="drawer-head"><div><p className="eyebrow">Phase 1</p><h2>Your demo cart</h2></div><button className="icon-btn" onClick={()=>setCartOpen(false)} aria-label="Close cart"><X/></button></div>{count===0?<div className="empty cart-empty"><ShoppingBag/><h3>Your cart is ready</h3><p>Add a few essentials to see them here.</p></div>:<><div className="cart-lines">{products.filter(p=>cart[p.id]).map(p=><div className="cart-line" key={p.id}><img src={p.image} alt=""/><div><strong>{p.name}</strong><small>₹{p.price.toLocaleString('en-IN')} · {p.unit}</small><div className="quantity"><button onClick={()=>change(p.id,-1)} aria-label="Decrease quantity"><Minus/></button><span>{cart[p.id]}</span><button onClick={()=>change(p.id,1)} aria-label="Increase quantity"><Plus/></button><button className="remove" onClick={()=>change(p.id,-cart[p.id])}>Remove</button></div></div><b>₹{(p.price*cart[p.id]).toLocaleString('en-IN')}</b></div>)}</div><div className="cart-total"><span>Subtotal</span><strong>₹{subtotal.toLocaleString('en-IN')}</strong></div></>}<p className="checkout-note">Checkout will be available after launch setup.</p></aside></div>}
    {assistant&&<div className="assistant"><div className="assistant-head"><div><strong>Pooja Assistant</strong><small>Guided demo assistant</small></div><button className="icon-btn" onClick={()=>setAssistant(false)} aria-label="Close assistant"><X/></button></div><div className="assistant-body"><div className="assistant-message">Namaste! I can help you explore the demo catalogue and find pooja essentials.</div>{['Find a Diwali kit','Browse daily pooja essentials','What is included in a kit?','Explore prasad ingredients','Help with my pooja checklist'].map(x=><button key={x} onClick={()=>{if(x.includes('Diwali'))scrollProducts('Pooja Kits','Diwali');else if(x.includes('prasad'))scrollProducts('Prasad & Bhog');else if(x.includes('daily'))scrollProducts('Daily Essentials');else if(x.includes('checklist'))document.querySelector('.checklist')?.scrollIntoView({behavior:'smooth'});setAssistant(false)}}>{x}<ArrowRight/></button>)}</div><div className="assistant-input"><input placeholder="Ask about the catalogue" aria-label="Ask the assistant"/><button aria-label="Send"><ArrowRight/></button></div></div>}
  </main>
}
