'use client'

import { useEffect, useMemo, useRef, useState } from 'react'
import Link from 'next/link'
import { ArrowRight, Check, ChevronDown, Menu, Minus, Plus, Search, ShoppingBag, Heart, X, Trash2, UserRound } from 'lucide-react'
import { categories, festivals, products, formatPrice, calculateCartSubtotal, matchesProductQuery, getCategory, getFestival, getProduct, faqs, type Product } from '@/lib/catalog'
import { Announcement, SearchDialog, AccountPanel } from './header-extras'
import { HeroSmoke } from './hero-smoke'
import { PoojaGuide } from './pooja-guide'
import { AssistantPanel } from './assistant-panel'

type Cart = Record<string, number>
const CART_KEY = 'poojasetu-cart'
const WISHLIST_KEY = 'poojasetu-wishlist'
const readIds = (key: string) => { try { const value = JSON.parse(localStorage.getItem(key) || '[]'); return Array.isArray(value) ? value.filter((id): id is string => typeof id === 'string') : [] } catch { return [] } }

export function Header() {
  const [open, setOpen] = useState(false)
  const [searchOpen, setSearchOpen] = useState(false)
  const [accountOpen, setAccountOpen] = useState(false)
  const [headerCart, setHeaderCart] = useState<Cart>({})
  const searchButton = useRef<HTMLButtonElement>(null)
  const accountButton = useRef<HTMLButtonElement>(null)
  const menuButton = useRef<HTMLButtonElement>(null)
  const closeMenu = () => { setOpen(false); requestAnimationFrame(() => menuButton.current?.focus()) }
  useEffect(() => {
    const updateCount = () => { try { const saved = JSON.parse(localStorage.getItem(CART_KEY) || '{}') as Record<string, unknown>; setHeaderCart(Object.fromEntries(Object.entries(saved).filter(([id, q]) => getProduct(id) && Number.isInteger(q) && (q as number) > 0).map(([id, q]) => [id, q as number]))) } catch { setHeaderCart({}) } }
    updateCount(); window.addEventListener('cart-change', updateCount); return () => window.removeEventListener('cart-change', updateCount)
  }, [])
  useEffect(() => { if (!open) return; const onKey = (e: KeyboardEvent) => { if (e.key === 'Escape') closeMenu() }; window.addEventListener('keydown', onKey); return () => window.removeEventListener('keydown', onKey) }, [open])
  const count = Object.values(headerCart).reduce((sum, quantity) => sum + quantity, 0)
  const subtotal = calculateCartSubtotal(headerCart)
  return <>
    <Announcement />
    <header className="header">
      <button ref={menuButton} className="icon-btn mobile-only" onClick={() => setOpen(true)} aria-label="Open navigation" aria-expanded={open}><Menu /></button>
      <Link className="logo" href="/"><span className="logo-mark" aria-hidden="true">✺</span><span><strong>DevaDwaar</strong><small>For every sacred occasion</small></span></Link>
      <nav className="desktop-nav" aria-label="Main navigation"><Link href="/shop">Shop All</Link><div className="nav-dropdown"><details><summary>Collections <ChevronDown /></summary><div className="nav-panel">{categories.map(c => <Link href={`/collections/${c.slug}`} key={c.slug}>{c.name}</Link>)}</div></details></div><Link href="/festivals">Festivals</Link><Link href="/collections/pooja-kits">Pooja Kits</Link><Link href="/collections/prasad-bhog">Prasad &amp; Bhog</Link><Link href="/pooja-guide">Pooja Guide</Link></nav>
      <div className="header-actions"><button ref={searchButton} className="icon-btn" onClick={() => setSearchOpen(true)} aria-label="Search products" aria-haspopup="dialog" aria-expanded={searchOpen}><Search /></button><Link className="icon-btn wishlist-header" href="/wishlist" aria-label="Wishlist"><Heart /></Link><button ref={accountButton} className="icon-btn account-trigger" onClick={() => setAccountOpen(true)} aria-label="Account" aria-haspopup="dialog" aria-expanded={accountOpen}><UserRound /></button><Link className="cart-btn" href="/cart" aria-label={`Cart with ${count} ${count === 1 ? 'item' : 'items'}, merchandise subtotal ${formatPrice(subtotal)}`}><ShoppingBag /><span>Cart <i aria-hidden="true">·</i> <strong>{formatPrice(subtotal)}</strong></span>{count > 0 && <b>{count}</b>}</Link></div>
    </header>
    {open && <><button className="menu-backdrop" aria-label="Close navigation" onClick={closeMenu} /><div className="mobile-menu" role="dialog" aria-modal="true" aria-label="Navigation"><div className="mobile-menu-head"><Link className="logo" href="/" onClick={closeMenu}><span className="logo-mark" aria-hidden="true">✺</span><strong>DevaDwaar</strong></Link><button className="icon-btn" onClick={closeMenu} aria-label="Close navigation"><X /></button></div><Link href="/shop" onClick={closeMenu}>Shop All</Link><details><summary>Collections <ChevronDown /></summary>{categories.map(c => <Link href={`/collections/${c.slug}`} key={c.slug} onClick={closeMenu}>{c.name}</Link>)}</details>{[['Festivals','/festivals'],['Pooja Kits','/collections/pooja-kits'],['Prasad & Bhog','/collections/prasad-bhog'],['Wishlist','/wishlist'],['Pooja Guide','/pooja-guide'],['Our Story','/about']].map(([label, href]) => <Link key={href} href={href} onClick={closeMenu}>{label}</Link>)}<button className="mobile-account-link" onClick={() => { setOpen(false); setAccountOpen(true) }}><UserRound /> Account</button></div></>}
    {searchOpen && <SearchDialog onClose={() => setSearchOpen(false)} triggerRef={searchButton} />}
    {accountOpen && <AccountPanel onClose={() => setAccountOpen(false)} triggerRef={accountButton} />}
  </>
}

function WishlistButton({ product }: { product: Product }) { const [saved, setSaved] = useState(false); useEffect(() => setSaved(readIds(WISHLIST_KEY).includes(product.id)), [product.id]); const toggle = () => { const next = readIds(WISHLIST_KEY).filter(id => id !== product.id); if (!saved) next.push(product.id); localStorage.setItem(WISHLIST_KEY, JSON.stringify(next)); setSaved(!saved); window.dispatchEvent(new Event('wishlist-change')) }; return <button className={`wishlist-button ${saved ? 'saved' : ''}`} aria-label={saved ? `Remove ${product.name} from wishlist` : `Add ${product.name} to wishlist`} aria-pressed={saved} onClick={e => { e.preventDefault(); toggle() }}><Heart fill={saved ? 'currentColor' : 'none'} /></button> }

export function ProductCard({ product, onAdd }: { product: Product; onAdd?: (id: string) => void }) { return <article className="product-card"><div className="product-media"><Link className="product-image" href={`/products/${product.slug}`}><img src={product.image} alt={product.name} width="600" height="600" loading="lazy" /></Link><WishlistButton product={product} /></div><div className="product-info"><p>{product.category}</p><h3><Link href={`/products/${product.slug}`}>{product.name}</Link></h3><small>{product.unit}</small><div className="product-bottom"><strong>{formatPrice(product.price)}</strong></div>{onAdd && <button className="add-button" onClick={() => onAdd(product.id)}>Add to Cart <Plus /></button>}</div></article> }

export function Storefront({ kind = 'home', slug }: { kind?: string; slug?: string }) {
  const [cart, setCart] = useState<Cart>({}); const [assistant, setAssistant] = useState(false); const [query, setQuery] = useState(''); const [category, setCategory] = useState(''); const [festival, setFestival] = useState(''); const [sort, setSort] = useState('featured')
  const [cartReady, setCartReady] = useState(false)
  useEffect(() => { if (kind === 'shop') setQuery(new URLSearchParams(window.location.search).get('q') || '') }, [kind])
  useEffect(() => { try { const saved = JSON.parse(localStorage.getItem(CART_KEY) || '{}'); if (saved && typeof saved === 'object') setCart(Object.fromEntries(Object.entries(saved).filter(([id, q]) => getProduct(id) && Number.isInteger(q) && (q as number) > 0).map(([id, q]) => [id, Math.min(q as number, 99)]))) } catch {} setCartReady(true) }, [])
  useEffect(() => { if (cartReady) { localStorage.setItem(CART_KEY, JSON.stringify(cart)); window.dispatchEvent(new Event('cart-change')) } }, [cart, cartReady])
  const add = (id: string) => setCart(c => ({ ...c, [id]: Math.min((c[id] || 0) + 1, 99) })); const change = (id: string, n: number) => setCart(c => { const next = { ...c }; const qty = (next[id] || 0) + n; if (qty <= 0) delete next[id]; else next[id] = Math.min(qty, 99); return next })
  const scoped = useMemo(() => { let list = products; if (kind === 'collection' && slug) list = list.filter(p => p.categorySlug === slug); if (kind === 'festival' && slug) list = list.filter(p => p.festivals.includes(slug)); if (category) list = list.filter(p => p.categorySlug === category); if (festival) list = list.filter(p => p.festivals.includes(festival)); if (query) list = list.filter(p => matchesProductQuery(p, query)); return [...list].sort((a, b) => sort === 'low' ? a.price - b.price : sort === 'high' ? b.price - a.price : products.indexOf(a) - products.indexOf(b)) }, [kind, slug, category, festival, query, sort])
  if (kind === 'product') return <><Header /><ProductDetail product={getProduct(slug || '')} add={add} /><Footer /><AssistantPanel open={assistant} setOpen={setAssistant} /></>
  if (kind === 'guide') return <><Header /><PoojaGuide add={add} /><Footer /><AssistantPanel open={assistant} setOpen={setAssistant} /></>
  if (kind === 'cart') return <><Header /><Cart cart={cart} change={change} /><Footer /><AssistantPanel open={assistant} setOpen={setAssistant} /></>
  if (kind === 'wishlist') return <><Header /><Wishlist add={add} /><Footer /><AssistantPanel open={assistant} setOpen={setAssistant} /></>
  if (kind === 'checkout') return <><Header /><Checkout cart={cart} /><Footer /></>
  if (kind === 'home') return <><Header /><Home add={add} /><Footer /><AssistantPanel open={assistant} setOpen={setAssistant} /></>
  const title = kind === 'collection' ? getCategory(slug || '')?.name : kind === 'festival' ? getFestival(slug || '')?.name : 'Shop all essentials'; const intro = kind === 'collection' ? getCategory(slug || '')?.description : kind === 'festival' ? getFestival(slug || '')?.description : 'Find thoughtfully prepared kits, daily samagri, offerings, lamps, and gifts for rituals at home.'
  return <><Header /><main className="site-shell"><section className={`page-hero ${kind === 'festival' ? 'festival-page-hero' : ''}`}><div className="container"><nav className="breadcrumbs" aria-label="Breadcrumb"><Link href="/">Home</Link> / {kind === 'festival' && <><Link href="/festivals">Festivals</Link> / </>}{title}</nav><p className="eyebrow">{kind === 'festival' ? 'Festival collection' : 'The collection'}</p><h1>{title || 'Collection'}</h1><p>{intro}</p></div>{kind === 'festival' && <img src={getFestival(slug || '')?.image} alt="" width="600" height="600" />}{kind === 'collection' && <img src={getCategory(slug || '')?.image} alt="" width="600" height="600" />}</section><section className="catalog section" id="catalog"><div className="container"><div className="shop-toolbar"><label className="search-wrap"><Search /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search essentials" aria-label="Search products" /></label><label className="sort-wrap">Sort by <select value={sort} onChange={e => setSort(e.target.value)} aria-label="Sort products"><option value="featured">Featured</option><option value="low">Price: low to high</option><option value="high">Price: high to low</option></select></label></div><div className="filter-row" aria-label="Filter categories"><button className={!category ? 'active' : ''} onClick={() => setCategory('')}>All</button>{categories.map(c => <button key={c.slug} className={category === c.slug ? 'active' : ''} onClick={() => setCategory(c.slug)}>{c.name}</button>)}</div><div className="results-line"><p className="result-count">Showing {scoped.length} {scoped.length === 1 ? 'item' : 'items'}</p>{(query || category || festival) && <button className="reset-button" onClick={() => { setQuery(''); setCategory(''); setFestival('') }}>Clear filters <X /></button>}</div>{scoped.length ? <div className="product-grid">{scoped.map(p => <ProductCard key={p.id} product={p} onAdd={add} />)}</div> : <div className="empty"><Search /><h3>No essentials found</h3><p>Try a different search or clear your filters.</p><button className="button secondary" onClick={() => { setQuery(''); setCategory(''); setFestival('') }}>Clear filters</button></div>}</div></section></main><Footer /><AssistantPanel open={assistant} setOpen={setAssistant} /></>
}

function Home({ add }: { add: (id: string) => void }) { return <main className="site-shell">
  <section className="hero"><img className="hero-photo" src="/hero-festive.webp" alt="Brass pooja thali with lit diyas, flowers, incense and offerings" width="1672" height="941" fetchPriority="high" /><div className="hero-shade" /><HeroSmoke /><div className="hero-copy container"><p className="eyebrow">Thoughtful essentials for sacred moments</p><h1>Everything for a meaningful pooja.</h1><p className="hero-text">Discover thoughtfully arranged kits, daily essentials, and festive offerings.</p><div className="hero-actions"><Link className="button primary" href="/collections/pooja-kits">Explore Pooja Kits <ArrowRight /></Link><Link className="text-button" href="/festivals">Shop Festival Essentials <ArrowRight /></Link></div></div></section>
  <section className="categories section"><div className="container"><div className="section-heading"><div><p className="eyebrow">Find your essentials</p><h2>Shop by Category</h2></div></div><div className="category-row">{categories.map(c => <Link className="category" href={`/collections/${c.slug}`} key={c.slug}><span className="category-image"><img src={c.image} alt="" width="600" height="600" loading="lazy" /></span><strong>{c.name}</strong></Link>)}</div></div></section>
  <section className="section festivals"><div className="container"><div className="section-heading"><div><p className="eyebrow">Celebrate together</p><h2>Shop by Festival</h2></div><Link className="section-link" href="/festivals">All festivals <ArrowRight /></Link></div><div className="festival-grid">{festivals.map(f => <Link className={`festival-card festival-${f.slug}`} href={`/festivals/${f.slug}`} key={f.slug}><span className="festival-image"><img src={f.image} alt="" width="600" height="600" loading="lazy" /></span><span className="festival-card-title">{f.name}<ArrowRight /></span><small>{f.description}</small></Link>)}</div></div></section>
  <section className="section featured"><div className="container"><div className="section-heading"><div><p className="eyebrow">Ready for the ritual</p><h2>Complete Pooja Kits</h2></div><Link className="section-link" href="/collections/pooja-kits">View all kits <ArrowRight /></Link></div><div className="product-grid">{products.filter(p => p.categorySlug === 'pooja-kits').map(p => <ProductCard product={p} onAdd={add} key={p.id} />)}</div></div></section>
  <section className="section daily"><div className="container"><div className="section-heading"><div><p className="eyebrow">Everyday rituals</p><h2>Daily Essentials</h2></div><Link className="section-link" href="/collections/daily-essentials">See essentials <ArrowRight /></Link></div><div className="product-grid">{['kapoor','agarbatti','diyas','kumkum'].map(id => { const p = getProduct(id)!; return <ProductCard product={p} onAdd={add} key={id} /> })}</div></div></section>
  <section className="editorial"><div className="editorial-image"><img src="/product-art/panchmeva.svg" alt="Illustration of panchmeva offering ingredients" width="600" height="600" loading="lazy" /></div><div className="editorial-copy"><p className="eyebrow">Offerings made with care</p><h2>Prasad &amp; Bhog</h2><p>Find ingredients for preparing and sharing offerings at home, from panchmeva to mishri.</p><Link className="button green" href="/collections/prasad-bhog">Explore the Collection <ArrowRight /></Link></div></section>
  <section className="section guide-teaser"><div className="container guide-teaser-inner"><div><p className="eyebrow">A helpful starting point</p><h2>Prepare with confidence.</h2><p>Choose an occasion, check what you already have, and gather the essentials that remain.</p><Link className="button outline" href="/pooja-guide">Open Pooja Guide <ArrowRight /></Link></div><span className="guide-ornament" aria-hidden="true">✺</span></div></section>
  <section className="section faq"><div className="container faq-inner"><div><p className="eyebrow">Good to know</p><h2>Questions, answered.</h2><p className="faq-intro">A little clarity before you begin shopping.</p></div><div className="faq-list">{faqs.map(([question, answer]) => <details key={question}><summary>{question}<Plus /></summary><p>{answer}</p></details>)}</div></div></section>
  </main> }

function ProductDetail({ product, add }: { product?: Product; add: (id: string) => void }) { const [quantity, setQuantity] = useState(1); const [notice, setNotice] = useState(false); if (!product) return <NotFound />; const related = products.filter(p => p.id !== product.id && (product.festivals.some(f => p.festivals.includes(f)) || p.categorySlug === product.categorySlug)).slice(0, 4); return <main className="product-detail section"><div className="container"><p className="breadcrumbs"><Link href="/">Home</Link> / <Link href="/shop">Shop</Link> / {product.name}</p><div className="detail-grid"><img className="detail-image" src={product.image} alt={`Illustration of ${product.name}`} width="600" height="600" /><div className="detail-copy"><p className="eyebrow">{product.category}</p><h1>{product.name}</h1><p className="detail-price">{formatPrice(product.price)} <small>{product.unit}</small></p><p className="detail-description">{product.description}</p><div className="detail-actions"><div className="quantity"><button aria-label="Decrease quantity" onClick={() => setQuantity(Math.max(1, quantity - 1))}><Minus /></button><span>{quantity}</span><button aria-label="Increase quantity" onClick={() => setQuantity(Math.min(99, quantity + 1))}><Plus /></button></div><button className="button primary" onClick={() => { for (let i = 0; i < quantity; i++) add(product.id); setNotice(true) }}>Add to Cart <ShoppingBag /></button><WishlistButton product={product} /></div>{notice && <p className="success-note" role="status"><Check /> Added to cart. <Link href="/cart">View cart</Link></p>}<div className="detail-notes"><h3>Good to know</h3>{product.details.map(x => <p key={x}>{x}</p>)}</div></div></div>{related.length > 0 && <section className="related"><h2>You may also need</h2><div className="product-grid">{related.map(p => <ProductCard key={p.id} product={p} onAdd={add} />)}</div></section>}</div></main> }

function Cart({ cart, change }: { cart: Cart; change: (id: string, n: number) => void }) { const items = products.filter(p => cart[p.id]); const subtotal = calculateCartSubtotal(cart); return <main className="section cart-page"><p className="eyebrow">Your shopping bag</p><h1>Your Cart</h1>{!items.length ? <div className="empty"><ShoppingBag /><h3>Your cart is empty.</h3><Link className="button primary" href="/shop">Continue Shopping</Link></div> : <><div className="cart-lines">{items.map(p => <div className="cart-line" key={p.id}><img src={p.image} alt="" /><div><Link href={`/products/${p.slug}`}><strong>{p.name}</strong></Link><small>{p.unit} · {formatPrice(p.price)} each</small><div className="quantity"><button aria-label={`Decrease ${p.name}`} onClick={() => change(p.id, -1)}><Minus /></button><span>{cart[p.id]}</span><button aria-label={`Increase ${p.name}`} onClick={() => change(p.id, 1)}><Plus /></button></div></div><b>{formatPrice(p.price * (cart[p.id] || 0))}</b><button className="icon-btn" aria-label={`Remove ${p.name}`} onClick={() => change(p.id, -(cart[p.id] || 0))}><Trash2 /></button></div>)}</div><div className="cart-total"><span>Merchandise subtotal</span><strong>{formatPrice(subtotal)}</strong></div><p className="checkout-note">Shipping and any applicable charges are not configured in this preview.</p><div className="hero-actions"><Link className="button secondary" href="/shop">Continue Shopping</Link><Link className="button primary" href="/checkout">Preview Order Summary</Link></div></>}</main> }

function Wishlist({ add }: { add: (id: string) => void }) { const [ids, setIds] = useState<string[]>([]); useEffect(() => { const sync = () => setIds(readIds(WISHLIST_KEY)); sync(); window.addEventListener('wishlist-change', sync); return () => window.removeEventListener('wishlist-change', sync) }, []); const saved = products.filter(p => ids.includes(p.id)); return <main className="section"><div className="container"><p className="eyebrow">Saved on this browser</p><h1>Wishlist</h1>{saved.length ? <div className="product-grid">{saved.map(p => <ProductCard key={p.id} product={p} onAdd={add} />)}</div> : <div className="empty"><Heart /><h3>Your wishlist is empty.</h3><p>Save essentials here while you browse.</p><Link className="button primary" href="/shop">Browse Shop</Link></div>}</div></main> }

function Checkout({ cart }: { cart: Cart }) { const items = products.filter(p => cart[p.id]); const subtotal = calculateCartSubtotal(cart); const [review, setReview] = useState(false); const [form, setForm] = useState({ name: '', email: '', mobile: '', address: '', city: '', state: '', pin: '' }); const [errors, setErrors] = useState<Record<string, string>>({}); const update = (key: string, value: string) => setForm(f => ({ ...f, [key]: value })); const submit = (e: React.FormEvent) => { e.preventDefault(); const next: Record<string, string> = {}; if (!form.name.trim()) next.name = 'Enter your full name.'; if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email)) next.email = 'Enter a valid email.'; if (!/^(?:\+91[-\s]?)?[6-9]\d{9}$/.test(form.mobile.replace(/[()]/g, ''))) next.mobile = 'Enter a valid Indian mobile number.'; if (!form.address.trim()) next.address = 'Enter your address.'; if (!form.city.trim()) next.city = 'Enter your city.'; if (!form.state.trim()) next.state = 'Enter your state or union territory.'; if (!/^\d{6}$/.test(form.pin)) next.pin = 'Enter a six-digit PIN code.'; setErrors(next); if (!Object.keys(next).length) setReview(true) }; if (!items.length) return <main className="section empty"><ShoppingBag /><h1>Your cart is empty</h1><p>Add products before opening the demo checkout.</p><Link className="button primary" href="/shop">Browse Shop</Link></main>; return <main className="section checkout-page"><div className="preview-notice"><strong>Demo checkout — no payment will be taken and no order will be placed.</strong><span>This preview does not verify address or delivery availability.</span></div>{review ? <><p className="eyebrow">Review</p><h1>Preview Order Summary</h1><div className="review-card"><h2>Delivery details</h2><p>{form.name}<br />{form.address}<br />{form.city}, {form.state} — {form.pin}<br />{form.email} · {form.mobile}</p><button className="button secondary" onClick={() => setReview(false)}>Edit Details</button></div><Summary items={items} cart={cart} subtotal={subtotal} /></> : <><p className="eyebrow">Guest checkout</p><h1>Preview your order</h1><div className="checkout-layout"><form className="checkout-form" onSubmit={submit} noValidate>{[['name','Full name','text'],['email','Email','email'],['mobile','Mobile number','tel'],['address','Address line 1','text'],['city','City','text'],['state','State or union territory','text'],['pin','PIN code','text']].map(([key, label, type]) => <label key={key}>{label}<input type={type} value={form[key as keyof typeof form]} onChange={e => update(key, e.target.value)} autoComplete={key === 'name' ? 'name' : key === 'email' ? 'email' : key === 'mobile' ? 'tel' : key === 'address' ? 'street-address' : key} aria-invalid={!!errors[key]} />{errors[key] && <small className="field-error">{errors[key]}</small>}</label>)}<button className="button primary" type="submit">Preview Order Summary</button></form><Summary items={items} cart={cart} subtotal={subtotal} /></div></>}</main> }
function Summary({ items, cart, subtotal }: { items: Product[]; cart: Cart; subtotal: number }) { return <aside className="summary"><h2>Merchandise summary</h2>{items.map(p => <p key={p.id}><span>{p.name} × {cart[p.id]}</span><strong>{formatPrice(p.price * cart[p.id])}</strong></p>)}<div className="cart-total"><span>Subtotal</span><strong>{formatPrice(subtotal)}</strong></div><small>Shipping and applicable charges are unavailable in this preview.</small></aside> }

export function Footer() { return <footer><div className="footer-brand"><Link className="logo" href="/"><span className="logo-mark" aria-hidden="true">✺</span><strong>DevaDwaar</strong></Link><p>Essentials for every sacred occasion.</p><small>Preview store — products and prices are illustrative. No orders or payments are placed.</small></div><div><strong>Shop</strong><Link href="/shop">All essentials</Link><Link href="/collections/pooja-kits">Pooja kits</Link><Link href="/collections/prasad-bhog">Prasad &amp; Bhog</Link><Link href="/wishlist">Wishlist</Link></div><div><strong>Explore</strong><Link href="/festivals">Festivals</Link><Link href="/pooja-guide">Pooja guide</Link><Link href="/about">Our story</Link></div></footer> }
function NotFound() { return <main className="section empty"><h1>We couldn&apos;t find that product.</h1><p>Try browsing the shop instead.</p><Link className="button primary" href="/shop">Shop essentials</Link></main> }
export { NotFound }
