'use client'

import { useEffect, useMemo, useState } from 'react'
import Link from 'next/link'
import { ArrowRight, Check, ChevronDown, Menu, Minus, Plus, Search, ShoppingBag, Heart, X, Trash2 } from 'lucide-react'
import { categories, festivals, products, formatPrice, getCategory, getFestival, getProduct, guideItems, type Product } from '@/lib/catalog'

type Cart = Record<string, number>
const CART_KEY = 'poojasetu-cart'
const WISHLIST_KEY = 'poojasetu-wishlist'
const readIds = (key: string) => { try { const value = JSON.parse(localStorage.getItem(key) || '[]'); return Array.isArray(value) ? value.filter((id): id is string => typeof id === 'string') : [] } catch { return [] } }

export function Header() {
  const [open, setOpen] = useState(false)
  return <>
    <div className="announcement">Preview store · Illustrative products and prices · No orders or payments are placed</div>
    <header className="header">
      <button className="icon-btn mobile-only" onClick={() => setOpen(true)} aria-label="Open navigation"><Menu /></button>
      <Link className="logo" href="/"><span className="diya" aria-hidden="true">◒</span><span><strong>DevaDwaar</strong><small>Essentials for every sacred occasion</small></span></Link>
      <nav className="desktop-nav"><Link href="/shop">Shop</Link><Link href="/festivals">Festivals</Link><Link href="/collections/pooja-kits">Pooja Kits</Link><Link href="/collections/prasad-bhog">Prasad &amp; Bhog</Link><Link href="/about">Our Story</Link></nav>
      <div className="header-actions"><Link className="icon-btn" href="/shop" aria-label="Search products"><Search /></Link><Link className="icon-btn" href="/wishlist" aria-label="Wishlist"><Heart /></Link><Link className="cart-btn" href="/cart" aria-label="Open cart"><ShoppingBag /><span>Cart</span></Link></div>
    </header>
    {open && <div className="mobile-menu" role="dialog" aria-label="Navigation"><div className="mobile-menu-head"><Link className="logo" href="/"><span className="diya" aria-hidden="true">◒</span><strong>DevaDwaar</strong></Link><button className="icon-btn" onClick={() => setOpen(false)} aria-label="Close navigation"><X /></button></div>{[['Shop','/shop'],['Festivals','/festivals'],['Pooja Kits','/collections/pooja-kits'],['Prasad & Bhog','/collections/prasad-bhog'],['Wishlist','/wishlist'],['Pooja Guide','/pooja-guide'],['Our Story','/about']].map(([label, href]) => <Link key={href} href={href} onClick={() => setOpen(false)}>{label}</Link>)}</div>}
  </>
}

function WishlistButton({ product }: { product: Product }) { const [saved, setSaved] = useState(false); useEffect(() => setSaved(readIds(WISHLIST_KEY).includes(product.id)), [product.id]); const toggle = () => { const next = readIds(WISHLIST_KEY).filter(id => id !== product.id); if (!saved) next.push(product.id); localStorage.setItem(WISHLIST_KEY, JSON.stringify(next)); setSaved(!saved); window.dispatchEvent(new Event('wishlist-change')) }; return <button className={`wishlist-button ${saved ? 'saved' : ''}`} aria-label={saved ? `Remove ${product.name} from wishlist` : `Add ${product.name} to wishlist`} aria-pressed={saved} onClick={e => { e.preventDefault(); toggle() }}><Heart fill={saved ? 'currentColor' : 'none'} /></button> }

export function ProductCard({ product, onAdd }: { product: Product; onAdd?: (id: string) => void }) { return <article className="product-card"><Link className="product-image" href={`/products/${product.slug}`}><img src={product.image} alt={product.name} /><span>View details <ArrowRight /></span><WishlistButton product={product} /></Link><div className="product-info"><p>{product.category}</p><h3><Link href={`/products/${product.slug}`}>{product.name}</Link></h3><small>{product.unit}</small><div className="product-bottom"><strong>{formatPrice(product.price)}</strong>{onAdd && <button className="add-button" onClick={() => onAdd(product.id)}>Add to cart <Plus /></button>}</div></div></article> }

export function Storefront({ kind = 'home', slug }: { kind?: string; slug?: string }) {
  const [cart, setCart] = useState<Cart>({}); const [assistant, setAssistant] = useState(false); const [query, setQuery] = useState(''); const [category, setCategory] = useState(''); const [festival, setFestival] = useState(''); const [sort, setSort] = useState('featured'); const [checked, setChecked] = useState<string[]>([]); const [occasion, setOccasion] = useState('Daily')
  useEffect(() => { try { const saved = JSON.parse(localStorage.getItem(CART_KEY) || '{}'); if (saved && typeof saved === 'object') setCart(Object.fromEntries(Object.entries(saved).filter(([id, q]) => getProduct(id) && Number.isInteger(q) && (q as number) > 0).map(([id, q]) => [id, Math.min(q as number, 99)]))) } catch {} }, [])
  useEffect(() => { localStorage.setItem(CART_KEY, JSON.stringify(cart)) }, [cart])
  const add = (id: string) => setCart(c => ({ ...c, [id]: Math.min((c[id] || 0) + 1, 99) })); const change = (id: string, n: number) => setCart(c => { const next = { ...c }; const qty = (next[id] || 0) + n; if (qty <= 0) delete next[id]; else next[id] = Math.min(qty, 99); return next })
  const scoped = useMemo(() => { let list = products; if (kind === 'collection' && slug) list = list.filter(p => p.categorySlug === slug); if (kind === 'festival' && slug) list = list.filter(p => p.festivals.includes(slug)); if (category) list = list.filter(p => p.categorySlug === category); if (festival) list = list.filter(p => p.festivals.includes(festival)); if (query) list = list.filter(p => `${p.name} ${p.category} ${p.festivals.join(' ')}`.toLowerCase().includes(query.toLowerCase())); return [...list].sort((a, b) => sort === 'low' ? a.price - b.price : sort === 'high' ? b.price - a.price : products.indexOf(a) - products.indexOf(b)) }, [kind, slug, category, festival, query, sort])
  if (kind === 'product') return <><Header /><ProductDetail product={getProduct(slug || '')} add={add} /></>
  if (kind === 'guide') return <><Header /><Guide checked={checked} setChecked={setChecked} occasion={occasion} setOccasion={setOccasion} add={add} /></>
  if (kind === 'cart') return <><Header /><Cart cart={cart} change={change} /></>
  if (kind === 'wishlist') return <><Header /><Wishlist cart={cart} add={add} /></>
  if (kind === 'checkout') return <><Header /><Checkout cart={cart} /></>
  if (kind === 'home') return <><Header /><Home add={add} /><Footer /><Assistant open={assistant} setOpen={setAssistant} /></>
  const title = kind === 'collection' ? getCategory(slug || '')?.name : kind === 'festival' ? getFestival(slug || '')?.name : 'Shop all essentials'; const intro = kind === 'collection' ? getCategory(slug || '')?.description : kind === 'festival' ? getFestival(slug || '')?.description : 'Find thoughtfully prepared kits, daily samagri, offerings, lamps, and gifts for rituals at home.'
  return <><Header /><main className="site-shell"><section className="page-hero"><p className="eyebrow">{kind === 'festival' ? 'Festival collection' : 'DevaDwaar shop'}</p><h1>{title || 'Collection'}</h1><p>{intro}</p></section><section className="catalog section"><div className="shop-toolbar"><div className="search-wrap"><Search /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search by name, category, or festival" aria-label="Search products" /></div><select value={sort} onChange={e => setSort(e.target.value)} aria-label="Sort products"><option value="featured">Featured</option><option value="low">Price: low to high</option><option value="high">Price: high to low</option></select></div><div className="filter-row"><button className={!category ? 'active' : ''} onClick={() => setCategory('')}>All categories</button>{categories.map(c => <button key={c.slug} className={category === c.slug ? 'active' : ''} onClick={() => setCategory(c.slug)}>{c.name}</button>)}</div><p className="result-count">{scoped.length} products</p>{scoped.length ? <div className="product-grid">{scoped.map(p => <ProductCard key={p.id} product={p} onAdd={add} />)}</div> : <div className="empty"><Search /><h3>No essentials found</h3><p>Try a different search or clear your filters.</p><button className="button secondary" onClick={() => { setQuery(''); setCategory(''); setFestival('') }}>Clear filters</button></div>}</section></main><Footer /><Assistant open={assistant} setOpen={setAssistant} /></>
}

function Home({ add }: { add: (id: string) => void }) { return <main className="site-shell"><section className="hero"><div className="hero-copy"><p className="eyebrow">Pooja essentials for every occasion</p><h1>Bring every ritual <em>together.</em></h1><p className="hero-text">Explore festive pooja kits, daily samagri, and thoughtful offerings for your home.</p><div className="hero-actions"><Link className="button primary" href="/festivals">Shop Festival Collections <ArrowRight /></Link><Link className="text-button" href="/collections/pooja-kits">Explore Pooja Kits</Link></div></div><div className="hero-art"><img src="/pooja-hero.png" alt="Festive pooja arrangement with lamps and offerings" /></div></section><section className="categories"><p className="eyebrow centered">Start with what you need</p><h2 className="centered">Shop by category</h2><div className="category-row">{categories.map(c => <Link className="category" href={`/collections/${c.slug}`} key={c.slug}><span className="category-image"><img src={c.image} alt="" /></span><strong>{c.name}</strong></Link>)}</div></section><section className="section featured"><div className="section-heading"><div><p className="eyebrow">Gathered with care</p><h2>Featured essentials.</h2></div><Link className="text-button dark-text" href="/shop">Shop all <ArrowRight /></Link></div><div className="product-grid">{products.slice(0, 8).map(p => <ProductCard product={p} onAdd={add} key={p.id} />)}</div></section></main> }

function ProductDetail({ product, add }: { product?: Product; add: (id: string) => void }) { const [quantity, setQuantity] = useState(1); const [notice, setNotice] = useState(false); if (!product) return <NotFound />; const related = products.filter(p => p.id !== product.id && (product.festivals.some(f => p.festivals.includes(f)) || p.categorySlug === product.categorySlug)).slice(0, 4); return <main className="product-detail section"><p className="breadcrumbs"><Link href="/shop">Shop</Link> / {product.name}</p><div className="detail-grid"><img className="detail-image" src={product.image} alt={product.name} /><div className="detail-copy"><p className="eyebrow">{product.category}</p><h1>{product.name}</h1><p className="detail-price">{formatPrice(product.price)} <small>{product.unit}</small></p><p className="detail-description">{product.description}</p><div className="quantity"><button aria-label="Decrease quantity" onClick={() => setQuantity(Math.max(1, quantity - 1))}><Minus /></button><span>{quantity}</span><button aria-label="Increase quantity" onClick={() => setQuantity(Math.min(99, quantity + 1))}><Plus /></button></div><button className="button primary" onClick={() => { for (let i = 0; i < quantity; i++) add(product.id); setNotice(true) }}>Add to Cart <ShoppingBag /></button><WishlistButton product={product} />{notice && <p className="success-note" role="status"><Check /> Added to cart. <Link href="/cart">View cart</Link></p>}<div className="detail-notes"><h3>Good to know</h3>{product.details.map(x => <p key={x}>{x}</p>)}</div></div></div>{related.length > 0 && <section className="related"><h2>You may also need</h2><div className="product-grid">{related.map(p => <ProductCard key={p.id} product={p} />)}</div></section>}</main> }

function Cart({ cart, change }: { cart: Cart; change: (id: string, n: number) => void }) { const items = products.filter(p => cart[p.id]); const subtotal = items.reduce((s, p) => s + p.price * (cart[p.id] || 0), 0); return <main className="section cart-page"><p className="eyebrow">Your shopping bag</p><h1>Your Cart</h1>{!items.length ? <div className="empty"><ShoppingBag /><h3>Your cart is empty.</h3><Link className="button primary" href="/shop">Continue Shopping</Link></div> : <><div className="cart-lines">{items.map(p => <div className="cart-line" key={p.id}><img src={p.image} alt="" /><div><Link href={`/products/${p.slug}`}><strong>{p.name}</strong></Link><small>{p.unit} · {formatPrice(p.price)} each</small><div className="quantity"><button aria-label={`Decrease ${p.name}`} onClick={() => change(p.id, -1)}><Minus /></button><span>{cart[p.id]}</span><button aria-label={`Increase ${p.name}`} onClick={() => change(p.id, 1)}><Plus /></button></div></div><b>{formatPrice(p.price * (cart[p.id] || 0))}</b><button className="icon-btn" aria-label={`Remove ${p.name}`} onClick={() => change(p.id, -(cart[p.id] || 0))}><Trash2 /></button></div>)}</div><div className="cart-total"><span>Merchandise subtotal</span><strong>{formatPrice(subtotal)}</strong></div><p className="checkout-note">Shipping and any applicable charges are not configured in this preview.</p><div className="hero-actions"><Link className="button secondary" href="/shop">Continue Shopping</Link><Link className="button primary" href="/checkout">Preview Order Summary</Link></div></>}</main> }

function Wishlist({ cart, add }: { cart: Cart; add: (id: string) => void }) { const [ids, setIds] = useState<string[]>([]); useEffect(() => { const sync = () => setIds(readIds(WISHLIST_KEY)); sync(); window.addEventListener('wishlist-change', sync); return () => window.removeEventListener('wishlist-change', sync) }, []); const saved = products.filter(p => ids.includes(p.id)); return <main className="section"><p className="eyebrow">Saved on this browser</p><h1>Wishlist</h1>{saved.length ? <div className="product-grid">{saved.map(p => <ProductCard key={p.id} product={p} onAdd={add} />)}</div> : <div className="empty"><Heart /><h3>Your wishlist is empty.</h3><p>Save essentials here while you browse.</p><Link className="button primary" href="/shop">Browse Shop</Link></div>}</main> }

function Checkout({ cart }: { cart: Cart }) { const items = products.filter(p => cart[p.id]); const subtotal = items.reduce((s, p) => s + p.price * (cart[p.id] || 0), 0); const [review, setReview] = useState(false); const [form, setForm] = useState({ name: '', email: '', mobile: '', address: '', city: '', state: '', pin: '' }); const [errors, setErrors] = useState<Record<string, string>>({}); const update = (key: string, value: string) => setForm(f => ({ ...f, [key]: value })); const submit = (e: React.FormEvent) => { e.preventDefault(); const next: Record<string, string> = {}; if (!form.name.trim()) next.name = 'Enter your full name.'; if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email)) next.email = 'Enter a valid email.'; if (!/^(?:\+91[-\s]?)?[6-9]\d{9}$/.test(form.mobile.replace(/[()]/g, ''))) next.mobile = 'Enter a valid Indian mobile number.'; if (!form.address.trim()) next.address = 'Enter your address.'; if (!form.city.trim()) next.city = 'Enter your city.'; if (!form.state.trim()) next.state = 'Enter your state or union territory.'; if (!/^\d{6}$/.test(form.pin)) next.pin = 'Enter a six-digit PIN code.'; setErrors(next); if (!Object.keys(next).length) setReview(true) }; if (!items.length) return <main className="section empty"><ShoppingBag /><h1>Your cart is empty</h1><p>Add products before opening the demo checkout.</p><Link className="button primary" href="/shop">Browse Shop</Link></main>; return <main className="section checkout-page"><div className="preview-notice"><strong>Demo checkout — no payment will be taken and no order will be placed.</strong><span>This preview does not verify address or delivery availability.</span></div>{review ? <><p className="eyebrow">Review</p><h1>Preview Order Summary</h1><div className="review-card"><h2>Delivery details</h2><p>{form.name}<br />{form.address}<br />{form.city}, {form.state} — {form.pin}<br />{form.email} · {form.mobile}</p><button className="button secondary" onClick={() => setReview(false)}>Edit Details</button></div><Summary items={items} subtotal={subtotal} /></> : <><p className="eyebrow">Guest checkout</p><h1>Preview your order</h1><form className="checkout-form" onSubmit={submit} noValidate>{[['name','Full name','text'],['email','Email','email'],['mobile','Mobile number','tel'],['address','Address line 1','text'],['city','City','text'],['state','State or union territory','text'],['pin','PIN code','text']].map(([key, label, type]) => <label key={key}>{label}<input type={type} value={form[key as keyof typeof form]} onChange={e => update(key, e.target.value)} autoComplete={key === 'name' ? 'name' : key === 'email' ? 'email' : key === 'mobile' ? 'tel' : key === 'address' ? 'street-address' : key} aria-invalid={!!errors[key]} />{errors[key] && <small className="field-error">{errors[key]}</small>}</label>)}<button className="button primary" type="submit">Preview Order Summary</button></form><Summary items={items} subtotal={subtotal} /></>}</main> }
function Summary({ items, subtotal }: { items: Product[]; subtotal: number }) { return <aside className="summary"><h2>Merchandise summary</h2>{items.map(p => <p key={p.id}><span>{p.name} × {1}</span><strong>{formatPrice(p.price)}</strong></p>)}<div className="cart-total"><span>Subtotal</span><strong>{formatPrice(subtotal)}</strong></div><small>Shipping and applicable charges are unavailable in this preview.</small></aside> }

function Guide({ checked, setChecked, occasion, setOccasion, add }: { checked: string[]; setChecked: (x: string[]) => void; occasion: string; setOccasion: (x: string) => void; add: (id: string) => void }) { const ids = guideItems[occasion] || []; return <main className="section guide-page"><p className="eyebrow">A simple starting point</p><h1>Prepare your pooja.</h1><p className="intro">Regional and family practices may vary. Use this as a helpful starting point.</p><div className="occasion-tabs">{Object.keys(guideItems).map(x => <button className={x === occasion ? 'active' : ''} key={x} onClick={() => { setOccasion(x); setChecked([]) }}>{x}</button>)}</div><p className="result-count">{checked.length} of {ids.length} essentials checked</p><div className="guide-list">{ids.map(id => { const p = getProduct(id); if (!p) return null; const done = checked.includes(id); return <div className={`guide-item ${done ? 'done' : ''}`} key={id}><button onClick={() => setChecked(done ? checked.filter(x => x !== id) : [...checked, id])}><span>{done && <Check />}</span><strong>{p.name}</strong><small>{p.unit}</small></button>{!done && <button className="text-button dark-text" onClick={() => add(id)}>Add to cart</button>}</div> })}</div>{checked.length === ids.length && <div className="complete"><Check /> Your suggested list is complete. Fresh or household items should be arranged separately.</div>}</main> }
function Assistant({ open, setOpen }: { open: boolean; setOpen: (x: boolean) => void }) { if (!open) return null; return <div className="assistant"><div className="assistant-head"><div><strong>Pooja Assistant</strong><small>Guided demo assistant</small></div><button className="icon-btn" onClick={() => setOpen(false)} aria-label="Close assistant"><X /></button></div><div className="assistant-body"><p>Namaste. I can help you explore this sample catalogue.</p><Link href="/festivals/diwali" onClick={() => setOpen(false)}>Find a Diwali collection <ArrowRight /></Link><Link href="/pooja-guide" onClick={() => setOpen(false)}>Open the pooja guide <ArrowRight /></Link><Link href="/cart" onClick={() => setOpen(false)}>Open my cart <ArrowRight /></Link></div></div> }
function Footer() { return <footer><div className="footer-brand"><Link className="logo" href="/"><span className="diya" aria-hidden="true">◒</span><strong>DevaDwaar</strong></Link><p>Essentials for every sacred occasion.</p><small>Preview store — products and prices are illustrative.</small></div><div><strong>Shop</strong><Link href="/shop">All essentials</Link><Link href="/collections/pooja-kits">Pooja kits</Link><Link href="/wishlist">Wishlist</Link></div><div><strong>Explore</strong><Link href="/festivals">Festivals</Link><Link href="/pooja-guide">Pooja guide</Link><Link href="/about">Our story</Link></div></footer> }
function NotFound() { return <main className="section empty"><h1>We couldn&apos;t find that product.</h1><p>Try browsing the shop instead.</p><Link className="button primary" href="/shop">Shop essentials</Link></main> }
export { NotFound }

const _unused = { ChevronDown }
void _unused
